window.HP_DATA={
 park:{address:'589 Hester Porter Road, Tuscumbia, AL 35674',phone:'(256) 349-4150',email:'info@hawkpridemountainoffroad.com'},
 passes:[{id:1,title:'1-Day Pass',price:20,desc:'Any single open day.',features:['Full trail access','Mud and ATV areas']},
  {id:2,title:'2-Day Pass',price:30,desc:'Two consecutive days.',features:['Full trail access','Primitive camping included'],highlight:true,badge:'Most popular'},
  {id:3,title:'3-Day Pass',price:40,desc:'Friday through Sunday.',features:['Full trail access','Primitive camping included']},
  {id:4,title:'4-Day Pass',price:50,desc:'Holiday and event weekends.',features:['Full trail access','Primitive camping included']}],
 events:[{id:'ratp',title:'Ride at the Pride',month:'APR',day:'24',dates:'Apr 24–26',type:'Park ride',status:'featured',price:'Standard passes',image:'../../assets/photos/event-crawl-crowd.jpg'},
  {id:'dsz',title:"Down South Zukin'",month:'MAY',day:'13',dates:'May 13–14',type:'Club ride',price:'Standard passes',image:'../../assets/photos/hillside-traffic.jpg'},
  {id:'mem',title:'Memorial Day Weekend',month:'MAY',day:'27',dates:'May 27–30',type:'Holiday ride',status:'few',price:'4-day pass $50',image:'../../assets/photos/pavilion-jeeps.jpg'},
  {id:'jul',title:'4th of July Weekend',month:'JUL',day:'1',dates:'Jul 1–4',type:'Holiday ride',price:'4-day pass $50'},
  {id:'srrs',title:'SRRS Hillclimb',month:'AUG',day:'12',dates:'Aug 12–13',type:'Hillclimb',price:'Spectator passes',image:'../../assets/photos/buggy-airborne.jpg'},
  {id:'mk',title:'Mardi Krawl',month:'AUG',day:'25',dates:'Aug 25–28',type:'Rock crawl',status:'soldout',price:'Register with club',image:'../../assets/photos/rock-ledge-buggies.jpg'}],
 lodging:[{id:'c1',name:'Ridge View Cabin',kind:'Cabin',sleeps:6,features:['A/C','Porch'],price:145,available:true},
  {id:'c2',name:'Cane Creek Cabin',kind:'Cabin',sleeps:4,features:['A/C','Grill'],price:125,available:true},
  {id:'c3',name:'Hawk Nest Cabin',kind:'Cabin',sleeps:8,features:['A/C','Bunk room'],price:175,available:false},
  {id:'r7',name:'RV Pad 7',kind:'RV site',sleeps:6,features:['50 amp','Water'],price:55,unit:'night',available:true},
  {id:'r2',name:'RV Pad 2',kind:'RV site',sleeps:6,features:['50 amp','Water'],price:55,available:true},
  {id:'p1',name:'Primitive camping',kind:'Camping',features:['Included with 2+ day pass'],price:0,unit:'night',available:true}],
 trails:[{number:'#07',name:'Cane Creek Loop',level:'easy',vehicles:'All vehicles',length:'3.2 mi'},
  {number:'#12',name:'Pine Ridge Run',level:'easy',vehicles:'ATV · SxS',length:'2.1 mi'},
  {number:'#23',name:'Bluff Line',level:'moderate',vehicles:'SxS · 4x4',length:'1.4 mi'},
  {number:'#31',name:'Hollow Crossing',level:'moderate',vehicles:'4x4 · Jeep',length:'0.9 mi'},
  {number:'#38',name:'Staircase',level:'difficult',vehicles:'Built 4x4 · Buggy',length:'0.6 mi'},
  {number:'#42',name:'Widowmaker',level:'extreme',vehicles:'Buggy only',length:'0.4 mi',status:'closed'},
  {number:'#57',name:'Ledges',level:'difficult',vehicles:'Built 4x4 · Buggy',length:'0.5 mi'},
  {number:'#61',name:'Rock Garden',level:'extreme',vehicles:'Buggy only',length:'0.3 mi'}]
};